### PR TITLE
fix: parameterize codebuild image

### LINKED ISSUE #175: Provisioning-Deprovisioning: (CodeBuild image)
### Describe the bug

The minimum version of node being used is 20 but the image used by the provisioning and deprovisioning codebuild is 18.

### Expected Behavior

A version of the above image containing node 20 should be used

### Current Behavior

The image used by the provisioning and deprovisioning codebuild has node 18

### Reproduction Steps

const codebuildProject = new codebuild.Project(this, `codebuildProject`, {
      source: props.source,
      encryptionKey: codeBuildProjectEncryptionKey,
      environment: {
        buildImage: codebuild.LinuxBuildImage.AMAZON_LINUX_2_5,
        privileged: true,
        environmentVariables: environmentVariables,
      },
      buildSpec: codebuild.BuildSpec.fromObject({
        version: '0.2',
        env: {
          shell: 'bash',
          'git-credential-helper': 'yes',
          ...(codeBuildProjectExportedVariables.length > 0 && {
            'exported-variables': codeBuildProjectExportedVariables,
          }),
        },
        phases: {
          build: {
            commands: props.script,
          },
          post_build: {
            ...(props.postScript && { commands: props.postScript }),
          },
        },
      }),
    });

### Possible Solution

_No response_

### Additional Information/Context

_No response_

### CDK CLI Version

0.8.2

### Framework Version

_No response_

### Node.js Version

20

### OS

linux

### Language

TypeScript

### Language Version

_No response_

### Other information

_No response_

### PR DESCRIPTION
**Pull request by arnel-sanchez**
### Issue #175

Closes #175.

### Reason for this change

The minimum version of node being used is 20 but the image used by the provisioning and deprovisioning codebuild is 18.

### Description of changes

Parameterize the image that will be used by code build and use the latest version of each language

### Description of how you validated changes

Running tests

### Checklist

- [ ] My code adheres to the [CONTRIBUTING GUIDE](https://github.com/awslabs/sbt-aws/blob/main/CONTRIBUTING.md)
- [ ] I have updated the relevant documentation (if applicable).

---

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the project license.*

### CODE REVIEW

File: src/core-app-plane/script-job.ts [hunk 1]
```diff
@@ -255,6 +265,18 @@ export class ScriptJob extends Construct {
...
+            ...(buildImage === defaultBuildImage && {
+              'runtime-versions': {
+                nodejs: 'latest',
+                python: 'latest',
+                java: 'latest',
+                ruby: 'latest',
+                golang: 'latest',
+                dotnet: 'latest',
+              },
+            }),
```
Comment (suhussai) [inline src/core-app-plane/script-job.ts:278]: I see what you're doing with the `buildImage === defaultBuildImage` check to ensure we only include the `runtime-versions` for the CodeBuild images that support them, but if you look at the docs, specifying `runtime-versions` only produces a warning for images that do not support them:

> If you specify a runtime-versions section and use an image other than Ubuntu Standard Image 2.0 or later, or the Amazon Linux 2 (AL2) standard image 1.0 or later, the build issues the warning, "Skipping install of runtimes. Runtime version selection is not supported by this build image."

https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html#build-spec.phases.install.runtime-versions

So, the check isn't necessary. It can also be problematic if let's say `codebuild.LinuxBuildImage.AMAZON_LINUX_2_6` comes out and a user specifies that, then `runtime-versions` won't be included because `buildImage === defaultBuildImage` will be false.

Hope that makes sense. Basically, I think we should get rid of the check and specify the `runtime-versions` regardless of which `buildImage` is used.

**Review by suhussai — CHANGES_REQUESTED** [review]
Great work! One minor feedback. TIA!

**Review by suhussai — APPROVED** [review]
LGTM!
